<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Mapster" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Papa.Facturacion.Dto\Papa.Facturacion.Dto.csproj" />
    <ProjectReference Include="..\Papa.Facturacion.Entities\Papa.Facturacion.Entities.csproj" />
    <ProjectReference Include="..\Papa.Facturacion.Repositories\Papa.Facturacion.Repositories.csproj" />
  </ItemGroup>

</Project>
